version: "3.9"

services:
  nginx-lb:
    image: nginx-lb:1.25-alpine
    container_name: nginx-lb-prod
    hostname: nginx-lb
    build: nginx
    environment:
      NGINX_ENTRYPOINT_LOCAL_RESOLVERS: 1
      DEFAULT_BACKEND: drupal-web:80
      HOST_FRONTEND_1: grav.lan
      HOST_FRONTEND_2: drupal.lan
      HOST_FRONTEND_3: ghost.lan
      HOST_BACKEND_1:  grav-web:80
      HOST_BACKEND_2:  drupal-web:80
      HOST_BACKEND_3:  ghost:80
    restart: always
    networks:
      - default
      - nginx-lb
    ports:
      - "80:80"
      - "443:443"


networks:
  default:
  nginx-lb:
    name: nginx-lb
    driver: overlay
